apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  database_name: {{ .Values.postgresql.auth.database }}
  database_port: {{ .Values.db.port | quote }}
  database_host: {{ include "fast-api.postgresHost" . }}
