apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.app.name }}"
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: host
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: database_host
            - name: database
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: database_name  
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: database_port
            - name: username
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: database_username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: database_password
 