apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.app.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: {{ .Values.app.name }}